require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GoddessesController do

  # This should return the minimal set of attributes required to create a valid
  # Goddess. As you add validations to Goddess, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "first_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GoddessesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all goddesses as @goddesses" do
      goddess = Goddess.create! valid_attributes
      get :index, {}, valid_session
      assigns(:goddesses).should eq([goddess])
    end
  end

  describe "GET show" do
    it "assigns the requested goddess as @goddess" do
      goddess = Goddess.create! valid_attributes
      get :show, {:id => goddess.to_param}, valid_session
      assigns(:goddess).should eq(goddess)
    end
  end

  describe "GET new" do
    it "assigns a new goddess as @goddess" do
      get :new, {}, valid_session
      assigns(:goddess).should be_a_new(Goddess)
    end
  end

  describe "GET edit" do
    it "assigns the requested goddess as @goddess" do
      goddess = Goddess.create! valid_attributes
      get :edit, {:id => goddess.to_param}, valid_session
      assigns(:goddess).should eq(goddess)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Goddess" do
        expect {
          post :create, {:goddess => valid_attributes}, valid_session
        }.to change(Goddess, :count).by(1)
      end

      it "assigns a newly created goddess as @goddess" do
        post :create, {:goddess => valid_attributes}, valid_session
        assigns(:goddess).should be_a(Goddess)
        assigns(:goddess).should be_persisted
      end

      it "redirects to the created goddess" do
        post :create, {:goddess => valid_attributes}, valid_session
        response.should redirect_to(Goddess.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved goddess as @goddess" do
        # Trigger the behavior that occurs when invalid params are submitted
        Goddess.any_instance.stub(:save).and_return(false)
        post :create, {:goddess => { "first_name" => "invalid value" }}, valid_session
        assigns(:goddess).should be_a_new(Goddess)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Goddess.any_instance.stub(:save).and_return(false)
        post :create, {:goddess => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested goddess" do
        goddess = Goddess.create! valid_attributes
        # Assuming there are no other goddesses in the database, this
        # specifies that the Goddess created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Goddess.any_instance.should_receive(:update).with({ "first_name" => "MyString" })
        put :update, {:id => goddess.to_param, :goddess => { "first_name" => "MyString" }}, valid_session
      end

      it "assigns the requested goddess as @goddess" do
        goddess = Goddess.create! valid_attributes
        put :update, {:id => goddess.to_param, :goddess => valid_attributes}, valid_session
        assigns(:goddess).should eq(goddess)
      end

      it "redirects to the goddess" do
        goddess = Goddess.create! valid_attributes
        put :update, {:id => goddess.to_param, :goddess => valid_attributes}, valid_session
        response.should redirect_to(goddess)
      end
    end

    describe "with invalid params" do
      it "assigns the goddess as @goddess" do
        goddess = Goddess.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Goddess.any_instance.stub(:save).and_return(false)
        put :update, {:id => goddess.to_param, :goddess => { "first_name" => "invalid value" }}, valid_session
        assigns(:goddess).should eq(goddess)
      end

      it "re-renders the 'edit' template" do
        goddess = Goddess.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Goddess.any_instance.stub(:save).and_return(false)
        put :update, {:id => goddess.to_param, :goddess => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested goddess" do
      goddess = Goddess.create! valid_attributes
      expect {
        delete :destroy, {:id => goddess.to_param}, valid_session
      }.to change(Goddess, :count).by(-1)
    end

    it "redirects to the goddesses list" do
      goddess = Goddess.create! valid_attributes
      delete :destroy, {:id => goddess.to_param}, valid_session
      response.should redirect_to(goddesses_url)
    end
  end

end
