require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MeditationsController do

  # This should return the minimal set of attributes required to create a valid
  # Meditation. As you add validations to Meditation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MeditationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all meditations as @meditations" do
      meditation = Meditation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:meditations).should eq([meditation])
    end
  end

  describe "GET show" do
    it "assigns the requested meditation as @meditation" do
      meditation = Meditation.create! valid_attributes
      get :show, {:id => meditation.to_param}, valid_session
      assigns(:meditation).should eq(meditation)
    end
  end

  describe "GET new" do
    it "assigns a new meditation as @meditation" do
      get :new, {}, valid_session
      assigns(:meditation).should be_a_new(Meditation)
    end
  end

  describe "GET edit" do
    it "assigns the requested meditation as @meditation" do
      meditation = Meditation.create! valid_attributes
      get :edit, {:id => meditation.to_param}, valid_session
      assigns(:meditation).should eq(meditation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Meditation" do
        expect {
          post :create, {:meditation => valid_attributes}, valid_session
        }.to change(Meditation, :count).by(1)
      end

      it "assigns a newly created meditation as @meditation" do
        post :create, {:meditation => valid_attributes}, valid_session
        assigns(:meditation).should be_a(Meditation)
        assigns(:meditation).should be_persisted
      end

      it "redirects to the created meditation" do
        post :create, {:meditation => valid_attributes}, valid_session
        response.should redirect_to(Meditation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved meditation as @meditation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Meditation.any_instance.stub(:save).and_return(false)
        post :create, {:meditation => { "name" => "invalid value" }}, valid_session
        assigns(:meditation).should be_a_new(Meditation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Meditation.any_instance.stub(:save).and_return(false)
        post :create, {:meditation => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested meditation" do
        meditation = Meditation.create! valid_attributes
        # Assuming there are no other meditations in the database, this
        # specifies that the Meditation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Meditation.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => meditation.to_param, :meditation => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested meditation as @meditation" do
        meditation = Meditation.create! valid_attributes
        put :update, {:id => meditation.to_param, :meditation => valid_attributes}, valid_session
        assigns(:meditation).should eq(meditation)
      end

      it "redirects to the meditation" do
        meditation = Meditation.create! valid_attributes
        put :update, {:id => meditation.to_param, :meditation => valid_attributes}, valid_session
        response.should redirect_to(meditation)
      end
    end

    describe "with invalid params" do
      it "assigns the meditation as @meditation" do
        meditation = Meditation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Meditation.any_instance.stub(:save).and_return(false)
        put :update, {:id => meditation.to_param, :meditation => { "name" => "invalid value" }}, valid_session
        assigns(:meditation).should eq(meditation)
      end

      it "re-renders the 'edit' template" do
        meditation = Meditation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Meditation.any_instance.stub(:save).and_return(false)
        put :update, {:id => meditation.to_param, :meditation => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested meditation" do
      meditation = Meditation.create! valid_attributes
      expect {
        delete :destroy, {:id => meditation.to_param}, valid_session
      }.to change(Meditation, :count).by(-1)
    end

    it "redirects to the meditations list" do
      meditation = Meditation.create! valid_attributes
      delete :destroy, {:id => meditation.to_param}, valid_session
      response.should redirect_to(meditations_url)
    end
  end

end
