require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MysticsController do

  # This should return the minimal set of attributes required to create a valid
  # Mystic. As you add validations to Mystic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MysticsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mystics as @mystics" do
      mystic = Mystic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mystics).should eq([mystic])
    end
  end

  describe "GET show" do
    it "assigns the requested mystic as @mystic" do
      mystic = Mystic.create! valid_attributes
      get :show, {:id => mystic.to_param}, valid_session
      assigns(:mystic).should eq(mystic)
    end
  end

  describe "GET new" do
    it "assigns a new mystic as @mystic" do
      get :new, {}, valid_session
      assigns(:mystic).should be_a_new(Mystic)
    end
  end

  describe "GET edit" do
    it "assigns the requested mystic as @mystic" do
      mystic = Mystic.create! valid_attributes
      get :edit, {:id => mystic.to_param}, valid_session
      assigns(:mystic).should eq(mystic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mystic" do
        expect {
          post :create, {:mystic => valid_attributes}, valid_session
        }.to change(Mystic, :count).by(1)
      end

      it "assigns a newly created mystic as @mystic" do
        post :create, {:mystic => valid_attributes}, valid_session
        assigns(:mystic).should be_a(Mystic)
        assigns(:mystic).should be_persisted
      end

      it "redirects to the created mystic" do
        post :create, {:mystic => valid_attributes}, valid_session
        response.should redirect_to(Mystic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mystic as @mystic" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mystic.any_instance.stub(:save).and_return(false)
        post :create, {:mystic => {  }}, valid_session
        assigns(:mystic).should be_a_new(Mystic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mystic.any_instance.stub(:save).and_return(false)
        post :create, {:mystic => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mystic" do
        mystic = Mystic.create! valid_attributes
        # Assuming there are no other mystics in the database, this
        # specifies that the Mystic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mystic.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => mystic.to_param, :mystic => { "these" => "params" }}, valid_session
      end

      it "assigns the requested mystic as @mystic" do
        mystic = Mystic.create! valid_attributes
        put :update, {:id => mystic.to_param, :mystic => valid_attributes}, valid_session
        assigns(:mystic).should eq(mystic)
      end

      it "redirects to the mystic" do
        mystic = Mystic.create! valid_attributes
        put :update, {:id => mystic.to_param, :mystic => valid_attributes}, valid_session
        response.should redirect_to(mystic)
      end
    end

    describe "with invalid params" do
      it "assigns the mystic as @mystic" do
        mystic = Mystic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mystic.any_instance.stub(:save).and_return(false)
        put :update, {:id => mystic.to_param, :mystic => {  }}, valid_session
        assigns(:mystic).should eq(mystic)
      end

      it "re-renders the 'edit' template" do
        mystic = Mystic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mystic.any_instance.stub(:save).and_return(false)
        put :update, {:id => mystic.to_param, :mystic => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mystic" do
      mystic = Mystic.create! valid_attributes
      expect {
        delete :destroy, {:id => mystic.to_param}, valid_session
      }.to change(Mystic, :count).by(-1)
    end

    it "redirects to the mystics list" do
      mystic = Mystic.create! valid_attributes
      delete :destroy, {:id => mystic.to_param}, valid_session
      response.should redirect_to(mystics_url)
    end
  end

end
