require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShareLinksController do

  # This should return the minimal set of attributes required to create a valid
  # ShareLink. As you add validations to ShareLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "url" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShareLinksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all share_links as @share_links" do
      share_link = ShareLink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:share_links).should eq([share_link])
    end
  end

  describe "GET show" do
    it "assigns the requested share_link as @share_link" do
      share_link = ShareLink.create! valid_attributes
      get :show, {:id => share_link.to_param}, valid_session
      assigns(:share_link).should eq(share_link)
    end
  end

  describe "GET new" do
    it "assigns a new share_link as @share_link" do
      get :new, {}, valid_session
      assigns(:share_link).should be_a_new(ShareLink)
    end
  end

  describe "GET edit" do
    it "assigns the requested share_link as @share_link" do
      share_link = ShareLink.create! valid_attributes
      get :edit, {:id => share_link.to_param}, valid_session
      assigns(:share_link).should eq(share_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ShareLink" do
        expect {
          post :create, {:share_link => valid_attributes}, valid_session
        }.to change(ShareLink, :count).by(1)
      end

      it "assigns a newly created share_link as @share_link" do
        post :create, {:share_link => valid_attributes}, valid_session
        assigns(:share_link).should be_a(ShareLink)
        assigns(:share_link).should be_persisted
      end

      it "redirects to the created share_link" do
        post :create, {:share_link => valid_attributes}, valid_session
        response.should redirect_to(ShareLink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved share_link as @share_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShareLink.any_instance.stub(:save).and_return(false)
        post :create, {:share_link => { "url" => "invalid value" }}, valid_session
        assigns(:share_link).should be_a_new(ShareLink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShareLink.any_instance.stub(:save).and_return(false)
        post :create, {:share_link => { "url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested share_link" do
        share_link = ShareLink.create! valid_attributes
        # Assuming there are no other share_links in the database, this
        # specifies that the ShareLink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ShareLink.any_instance.should_receive(:update).with({ "url" => "MyString" })
        put :update, {:id => share_link.to_param, :share_link => { "url" => "MyString" }}, valid_session
      end

      it "assigns the requested share_link as @share_link" do
        share_link = ShareLink.create! valid_attributes
        put :update, {:id => share_link.to_param, :share_link => valid_attributes}, valid_session
        assigns(:share_link).should eq(share_link)
      end

      it "redirects to the share_link" do
        share_link = ShareLink.create! valid_attributes
        put :update, {:id => share_link.to_param, :share_link => valid_attributes}, valid_session
        response.should redirect_to(share_link)
      end
    end

    describe "with invalid params" do
      it "assigns the share_link as @share_link" do
        share_link = ShareLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShareLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => share_link.to_param, :share_link => { "url" => "invalid value" }}, valid_session
        assigns(:share_link).should eq(share_link)
      end

      it "re-renders the 'edit' template" do
        share_link = ShareLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShareLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => share_link.to_param, :share_link => { "url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested share_link" do
      share_link = ShareLink.create! valid_attributes
      expect {
        delete :destroy, {:id => share_link.to_param}, valid_session
      }.to change(ShareLink, :count).by(-1)
    end

    it "redirects to the share_links list" do
      share_link = ShareLink.create! valid_attributes
      delete :destroy, {:id => share_link.to_param}, valid_session
      response.should redirect_to(share_links_url)
    end
  end

end
